spring:
  application:
    name: NationalEngineeringEnterpriseService
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/nationalengineering
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

